name: Generate articles.json

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate articles.json
        run: |
          node scripts/generate-articles-json.js

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add articles.json
          git commit -m "Auto-update articles.json" || echo "No changes to commit"
          git push