name: Update Articles JSON

on:
  push:
    branches: [main]
    paths:
      - 'press-releases/**'
      - 'record-release-notes/**'
      - '.github/workflows/update-articles.yml'
      - 'generate-articles-json.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies (if needed)
      run: |
        npm install

    - name: Run JSON generator
      run: node generate-articles-json.js

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Update articles.json automatically'